[project]
name = "rag-ai-assistent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "pgvector>=0.5.0",
    "psycopg[binary]>=3.3.5",
    "sentence-transformers>=6.0.1",
    "sqlalchemy>=2.0.53",
    "uvicorn[standard]>=0.53.0",
]
